### ISSUE TITLE
Problems With Templates?

### ISSUE THREAD

**Issue by HarshPatel5940** [srm-kzilla/fury#422]
# Issue In

- [x] Documentation

---

The templates which are created in `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md
` end with an `'+`. 
Is this intensional?  if not i would like to work on the PR for this chore (fix).

**Comment by shawshankkumar** [comment]
@SaanviKumar13 what do you think

**Comment by SaanviKumar13** [comment]
I think we can remove it since all it does is act like a placeholder to add the files which is not required since it's already mentioned to add them.
