### ISSUE TITLE
Incorrect Filename

### ISSUE THREAD

**Issue by HarshPatel5940** [srm-kzilla/fury#425]
# Issue In

- [x] Backend

# Expected Behavior

- file name should be: `api/models/admin.model.go`

# Current Behavior

- file name currently is: `api/models/admin.controller.go`

## Failure Logs

None

**Comment by Prasanjit-4** [comment]
Can I fix this?

**Comment by shawshankkumar** [comment]
> Can I fix this?

Sure why not?
